apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-gsviec
  name: php-gsviec
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: php-gsviec
